plugins { id 'com.android.application' }

android {
    buildFeatures { buildConfig true }
    namespace 'com.abosultan.darbakvehiclehub'
    compileSdk 34

    defaultConfig {
        applicationId 'com.abosultan.darbakvehiclehub'
        minSdk 25
        targetSdk 28
        versionCode 3
        versionName '0.3.0'
    }
}
