plugins { id 'com.android.application' }

android {
    buildFeatures { buildConfig true }
    namespace 'com.abosultan.darbakvehiclehub'
    compileSdk 34

    defaultConfig {
        applicationId 'com.abosultan.darbakvehiclehub'
        minSdk 25
        targetSdk 28
        versionCode 5
        versionName '0.3.2'
    }
}


dependencies {
    implementation 'androidx.core:core:1.9.0'
}
